name: SpigotEasyPlaceProtocol
description: Implements the Carpet AccurateBlockPlacement functionality on Spigot.
version: 1.21.1
authors: [DungeonDev, shou692199]
main: dev.tokasen.easyplaceprotocol.EasyPlaceProtocol
api-version: 1.21
depend: [ProtocolLib]
