name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # <<< Нужно для создания релиза

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle 8.8
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.8"

    - name: Install Spigot BuildTools
      uses: SpraxDev/Action-SpigotMC@v5
      with:
        versions: 1.21.1
        remapped: true

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload JAR to GitHub Release  # <<< ДОБАВЛЕН ШАГ
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
